source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 6.0.0.rc1'

gem 'activerecord-import'
gem 'apollo_upload_server', '2.0.0.beta.3'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.3.2', require: false
gem 'fuubar'
gem 'graphql-batch', '~> 0.3.10'
gem 'graphql-errors', '~> 0.3.0'
gem 'graphql', '~> 1.8.13'
gem 'jwt', '~> 2.1.0'
gem 'pg','>=0.18','<2.0'
gem 'puma', '~> 3.12.6'
gem 'rails-i18n', '~> 5.1'
gem 'sentry-raven', '~> 2.8.0'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubycritic', require: false
  gem 'spring'
end

group :test do
  gem 'activerecord-nulldb-adapter', '~> 0.3.9'
  gem 'shoulda-matchers', '~> 4.0.0.rc1'
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'factory_bot_rails', '~> 5.0.0.rc2'
  gem 'guard-rails'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.8'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
